stages:
  - publish

publish-package:
  stage: publish
  image: node:10.15.3-alpine
  cache:
    paths:
      - node_modules
  before_script:
    - echo //gitlab.sima-land.ru/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN} > .npmrc
    - npm --no-git-tag-version version $CI_COMMIT_REF_NAME
    - npm install
    - npm run dist
  script:
    - npm publish build
  only:
    refs:
      - tags
  tags:
    - sl-frontend

pages:
  stage: publish
  script:
  - npm run build
  - npm run build:docs
  artifacts:
    paths:
    - docs-build
  only:
  - master
  tags:
    - sl-frontend
